[package]
name = "mission-planner-c"
version = "0.1.0"
edition = "2024"
crate-type = ["staticlib"]

[dependencies]
mission_planner = {path = "../mission-planner" }

[build-dependencies]
bindgen = "0.72.0"
cbindgen = "0.29.0"
cc = "1.2.31"
