services:
  sam2-data-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: sam2-data-engine:latest
    container_name: sam2_data_engine

    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # X11 Display support
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth

    # Mount X11 socket and auth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./data:/app/data:rw
      - ./cache:/app/cache:rw
      - ./projects:/app/projects:rw
      - ./exports:/app/exports:rw
      - ./videos:/app/videos:ro

    privileged: True
    network_mode: host
