version: '3.8'

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    ports:
      - "11311:11311"
    ulimits:
      nofile:
        soft: 1024
        hard: 524288

  zed-camera:
    build:
      context: ../../hydrus-software-stack
      dockerfile: docker/amd64/cuda/camera.Dockerfile
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=${DISPLAY}
      - ZED_OPTION=${ZED_OPTION}
    depends_on:
      - ros-master
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    volumes:
      - "../:/home/catkin_ws/src"
      - /tmp/.X11-unix:/tmp/.X11-unix

  hydrus_cuda:
    build:
      context: ../../hydrus-software-stack
      dockerfile: docker/amd64/cuda/hydrus.Dockerfile
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - "../:/home/catkin_ws/src/hydrus-software-stack"
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "../rosbags:/rosbags"
      - "../yolo_models:/yolo_models"  # Volume for YOLO models
    ports:
      - "8000:8000"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"  # Added ttyACM1 mapping
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Added ttyUSB0 mapping
      - "/dev/dri:/dev/dri"
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ARDUINO_BOARD=arduino:avr:uno
      - VOLUME
      - ROSBAG_PLAYBACK
      - DEBUG_ARDUINO
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY variable from the host
      - RVIZ
      - TEST
      - NO_BUILD
      - TMUX_SESSIONS
      - ARDUINO_COMPILE
      - VIRTUAL_ARDUINO
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ZED_OPTION=${ZED_OPTION}
    depends_on:
      - ros-master
      - zed-camera
    restart: unless-stopped  # Added restart policy
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
